# Aula 13 (03/12/2019)

In [3]:
import numpy as np

## Exercícios de revisão

**3.2.** Faça uma função que gera uma matriz aleatória $X$ (escolha a distribuição) com $n$ linhas e $p$ colunas e um vetor $\vec{y}$, cujos valores são função das linhas de $X$ com adição de ruído normal, de média $0$ e variância $1$, e.g. $y_{i} = 3x_{i1} + 5x_{i2} + 10 + e_{i}$ , onde  $e_{i}∼N(0,1)$. Os parâmetros da função geradora devem incluir $n$, $p$ e a função geradora de $y$ (dica: use o operador **lambda**).

In [1]:
def generate_data(f, n = 2, p = 2):
    X = np.random.random((n, p))
    
    y = f(X) + np.random.normal(0, 1, n)
    
    return X, y

In [4]:
np.random.seed(3122019)

f = lambda x: 2*x[:,0]**2 + 3*x[:,1] + 1

X, y = generate_data(f,2,2)

X,y

(array([[0.38140576, 0.79472444],
        [0.83723106, 0.29058078]]), array([3.53992273, 2.60414624]))

**3.3.** Implemente uma classe *LinearRegression*, com os métodos:

- *fit* que recebe uma matriz $X$ e um vetor $\vec{y}$ e ajusta uma regressão linear pelo método dos mínimos quadrados, guardando os coeficientes e o intercept como atributos;
- *predict* que recebe uma matriz  $X$  e estima os valores $\hat{y}$ correspondentes;
- *score* que recebe uma matriz  $X$  e um vetor $\vec{y}$ e calcula o erro quadrático médio de estimação.

Use a função geradora da questão anterior para gerar  $X_{1}$  e $\vec{y}_{1}$ e ajustar o seu modelo e depois gerar $X_{2}$ e $\vec{y}_{2}$  e avaliar o modelo ajustado.

In [5]:
class LinearRegression:
    def fit(self,X,y):
        self.coef = np.linalg.inv(X.transpose() @ X) @ X.transpose() @ y
        return self # Permite usar o objeto assim que criado
    
    def predict(self, X):
        return X @ self.coef
    
    def score(self, X, y):
        return np.mean((y - self.predict(X))**2)

In [7]:
np.random.seed(3122019)

f = lambda x: 2*x[:,0]**2 + 3*x[:,1] + 1

X, y = generate_data(f,5,2)

# X = np.random.random((5,5))
# y = np.apply_along_axis(sum, 1, X) + np.random.normal(3, 2, 5)

print(X)
print()
print(y)
print()

LR = LinearRegression().fit(X,y)
print('Coeficientes:',LR.coef)
print()
print('Predição:',LR.predict(X))
print()
print('E.Q.M.:', LR.score(X,y))

[[0.38140576 0.79472444]
 [0.83723106 0.29058078]
 [0.06384561 0.41192892]
 [0.73589209 0.52317554]
 [0.00228603 0.53305588]]

[3.89229626 3.39653594 1.88252056 4.14314732 1.93126192]

Coeficientes: [2.85078609 3.68470903]

Predição: [4.01563454 3.45747228 1.69984839 4.02562056 1.97067279]

E.Q.M.: 0.013532089274704168
